" vim:set foldmethod=marker:
" defalult setting generate by :mkvimrc {{{1
version 6.0
if &cp | set nocp | endif
let s:cpo_save=&cpo
set cpo&vim
let &cpo=s:cpo_save
unlet s:cpo_save
set fileencodings=ucs-bom,utf-8,default,latin1
set helplang=en
set printoptions=paper:letter
set runtimepath=~/.vim,/var/lib/vim/addons,/usr/share/vim/vimfiles,/usr/share/vim/vim74,/usr/share/vim/vimfiles/after,/var/lib/vim/addons/after,~/.vim/after
set suffixes=.bak,~,.swp,.o,.info,.aux,.log,.dvi,.bbl,.blg,.brf,.cb,.ind,.idx,.ilg,.inx,.out,.toc 
"}}}
" remap the leader key {{{1
let mapleader="\<Space>"
let g:mapleader="\<Space>"
"}}}
" source my own scripts
source ~/.vim/abbreviations.vim
source ~/.vim/vimrc.vim
